package com.netease.gather.classifier.naivebayes;

import org.apache.commons.collections.keyvalue.DefaultKeyValue;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * User: AzraelX
 * Date: 13-10-12
 * Time: 上午11:14
 */
public class TopicInit {

    public static List<DefaultKeyValue> flattpc = new ArrayList<DefaultKeyValue>();
    public static List<DefaultKeyValue> chantpc = new ArrayList<DefaultKeyValue>();
    public static Map<String,List<DefaultKeyValue>> chancol = new HashMap<String,List<DefaultKeyValue>>();

    static {
        flattpc.add(new DefaultKeyValue("guonei", "0001124J"));
//        catetopicids.put("guonei","0001124K");
        flattpc.add(new DefaultKeyValue("guoji", "0001121M"));
//        catetopicids.put("guoji","0001121N");
        flattpc.add(new DefaultKeyValue("shehui", "00011229"));
//        catetopicids.put("shehui","0001122A");
        flattpc.add(new DefaultKeyValue("junshi", "00014OVF"));
//        catetopicids.put("junshi","00014OGN");
//        flattpc.add(new DefaultKeyValue("hangkong", "00014P42"));
        flattpc.add(new DefaultKeyValue("mingxing", "00031H2L"));
//        catetopicids.put("mingxing","00034RI5");
        flattpc.add(new DefaultKeyValue("yinyue", "00034KRO"));
//        catetopicids.put("yinyue","00034QNK");
        flattpc.add(new DefaultKeyValue("dianshi", "00031GVS"));
//        catetopicids.put("dianshi","00034QNN");
        flattpc.add(new DefaultKeyValue("dianying", "000300B1"));
//        catetopicids.put("dianying","00034QNJ");
        flattpc.add(new DefaultKeyValue("zonghetiyu", "00051CBI"));
        flattpc.add(new DefaultKeyValue("zonghetiyu", "00052IFL"));
//        flattpc.add(new DefaultKeyValue("yishuticao", "00052IFL"));
        flattpc.add(new DefaultKeyValue("zonghetiyu", "00053UBL"));
//        flattpc.add(new DefaultKeyValue("gaoerfu", "00053UBL"));
        flattpc.add(new DefaultKeyValue("saiche", "00051CAS"));
//        flattpc.add(new DefaultKeyValue("zixingche", "00051CAS"));
        flattpc.add(new DefaultKeyValue("zonghetiyu", "00052IF8"));
//        flattpc.add(new DefaultKeyValue("jijian", "00052IF8"));
        flattpc.add(new DefaultKeyValue("zonghetiyu", "00052IF6"));
//        flattpc.add(new DefaultKeyValue("mashu", "00052IF6"));
        flattpc.add(new DefaultKeyValue("zonghetiyu", "00052IFH"));
//        flattpc.add(new DefaultKeyValue("saiting", "00052IFH"));
        flattpc.add(new DefaultKeyValue("zonghetiyu", "00052IFE"));
//        flattpc.add(new DefaultKeyValue("pihuating", "00052IFE"));
        flattpc.add(new DefaultKeyValue("zonghetiyu", "00052IFB"));
//        flattpc.add(new DefaultKeyValue("fanchuan", "00052IFB"));
        flattpc.add(new DefaultKeyValue("zonghetiyu", "00052IFO"));
//        flattpc.add(new DefaultKeyValue("bengchuang", "00052IFO"));
        flattpc.add(new DefaultKeyValue("zonghetiyu", "0005038F"));
//        flattpc.add(new DefaultKeyValue("ganlanqiu", "0005038F"));
        flattpc.add(new DefaultKeyValue("zonghetiyu", "00052IFM"));
//        flattpc.add(new DefaultKeyValue("qugunqiu", "00052IFM"));
        flattpc.add(new DefaultKeyValue("zonghetiyu", "00052IFA"));
//        flattpc.add(new DefaultKeyValue("shouqiu", "00052IFA"));
        flattpc.add(new DefaultKeyValue("zonghetiyu", "00052IFG"));
//        flattpc.add(new DefaultKeyValue("shejia", "00052IFG"));
        flattpc.add(new DefaultKeyValue("zonghetiyu", "00052AFL"));
//        flattpc.add(new DefaultKeyValue("sheji", "00052AFL"));
        flattpc.add(new DefaultKeyValue("zonghetiyu", "00052IFD"));
//        flattpc.add(new DefaultKeyValue("taiquandao", "00052IFD"));
        flattpc.add(new DefaultKeyValue("zonghetiyu", "00052IFR"));
//        flattpc.add(new DefaultKeyValue("roudao", "00052IFR"));
        flattpc.add(new DefaultKeyValue("zonghetiyu", "00052IF7"));
//        flattpc.add(new DefaultKeyValue("shuaijiao", "00052IF7"));
        flattpc.add(new DefaultKeyValue("zonghetiyu", "00051CB8"));
//        flattpc.add(new DefaultKeyValue("quanji", "00051CB8"));
        flattpc.add(new DefaultKeyValue("zonghetiyu", "00052IFC"));
//        flattpc.add(new DefaultKeyValue("juzhong", "00052IFC"));
//        flattpc.add(new DefaultKeyValue("aoyun", "00053UAR"));
//        flattpc.add(new DefaultKeyValue("liuxiang", "000521B8"));
        flattpc.add(new DefaultKeyValue("zonghetiyu", "00051CAT"));
//        flattpc.add(new DefaultKeyValue("bingxue", "00051CAT"));
        flattpc.add(new DefaultKeyValue("zonghetiyu", "00051CB6"));
//        flattpc.add(new DefaultKeyValue("ticao", "00051CB6"));
        flattpc.add(new DefaultKeyValue("wangyuping", "00051L24"));
//        flattpc.add(new DefaultKeyValue("yumaoqiu", "00051L24"));
        flattpc.add(new DefaultKeyValue("zonghetiyu", "00052IF4"));
//        flattpc.add(new DefaultKeyValue("youyongtiaoshu", "00052IF4"));
        flattpc.add(new DefaultKeyValue("tianjing", "00051CB5"));
//        flattpc.add(new DefaultKeyValue("tianjing", "00051CB5"));
        flattpc.add(new DefaultKeyValue("wangyuping", "00051L23"));
//        flattpc.add(new DefaultKeyValue("pingpang", "00051L23"));
        flattpc.add(new DefaultKeyValue("taiqiu", "00051ROF"));
//        flattpc.add(new DefaultKeyValue("taiqiu", "00051ROF"));
        flattpc.add(new DefaultKeyValue("zonghetiyu", "00051CB9"));
//        flattpc.add(new DefaultKeyValue("qipai", "00051CB9"));
        flattpc.add(new DefaultKeyValue("paiqiu", "00051CB7"));
//        flattpc.add(new DefaultKeyValue("paiqiu", "00051CB7"));
        flattpc.add(new DefaultKeyValue("saiche", "00051CDQ"));
//        flattpc.add(new DefaultKeyValue("f1", "00051CDQ"));
        flattpc.add(new DefaultKeyValue("wangyuping", "00051CDG"));
//        flattpc.add(new DefaultKeyValue("wangqiu", "00051CDG"));
        flattpc.add(new DefaultKeyValue("cba", "00052UUC"));
        flattpc.add(new DefaultKeyValue("nba", "00051CA1"));
        flattpc.add(new DefaultKeyValue("guoneizuqiu", "00051C89"));
        flattpc.add(new DefaultKeyValue("guojizuqiu", "00051C9Q"));
        flattpc.add(new DefaultKeyValue("tongxin", "000915BE"));
        flattpc.add(new DefaultKeyValue("hulianwang", "000915BF"));
        flattpc.add(new DefaultKeyValue("ityejie", "000915BD"));
        flattpc.add(new DefaultKeyValue("zhengquan", "00251LIE"));
        flattpc.add(new DefaultKeyValue("zhengquan", "00251LJJ"));
        flattpc.add(new DefaultKeyValue("zhengquan", "00254SU7"));
        flattpc.add(new DefaultKeyValue("hongguan", "00252G50"));
//        flattpc.add(new DefaultKeyValue("hongguan", "00252C1E"));
        flattpc.add(new DefaultKeyValue("chanjing", "002534NU"));
        flattpc.add(new DefaultKeyValue("chanjing", "002534NV"));
        flattpc.add(new DefaultKeyValue("chanjing", "002526O3"));
        flattpc.add(new DefaultKeyValue("chanjing", "002524SO"));
        flattpc.add(new DefaultKeyValue("chanjing", "002526O5"));
        flattpc.add(new DefaultKeyValue("jinrong", "00252H36"));
        flattpc.add(new DefaultKeyValue("jinrong", "00254SK6"));
//        flattpc.add(new DefaultKeyValue("shangye", "00252FE1"));


        chantpc.add(new DefaultKeyValue("news", "0001124J"));
        chantpc.add(new DefaultKeyValue("news", "0001121M"));
        chantpc.add(new DefaultKeyValue("news", "00011229"));
        chantpc.add(new DefaultKeyValue("news", "00014OVF"));
//        chantpc.add(new DefaultKeyValue("news", "00014P42"));
        chantpc.add(new DefaultKeyValue("ent", "00031H2L"));
        chantpc.add(new DefaultKeyValue("ent", "00034KRO"));
        chantpc.add(new DefaultKeyValue("ent", "00031GVS"));
        chantpc.add(new DefaultKeyValue("ent", "000300B1"));
        chantpc.add(new DefaultKeyValue("sports", "00051CBI"));
        chantpc.add(new DefaultKeyValue("sports", "00053UBL"));
        chantpc.add(new DefaultKeyValue("sports", "00051CAS"));
        chantpc.add(new DefaultKeyValue("sports", "00052IF8"));
        chantpc.add(new DefaultKeyValue("sports", "00052IF6"));
        chantpc.add(new DefaultKeyValue("sports", "00052IFH"));
        chantpc.add(new DefaultKeyValue("sports", "00052IFE"));
        chantpc.add(new DefaultKeyValue("sports", "00052IFB"));
        chantpc.add(new DefaultKeyValue("sports", "00052IFO"));
        chantpc.add(new DefaultKeyValue("sports", "00052IFL"));
        chantpc.add(new DefaultKeyValue("sports", "0005038F"));
        chantpc.add(new DefaultKeyValue("sports", "00052IFM"));
        chantpc.add(new DefaultKeyValue("sports", "00052IFA"));
        chantpc.add(new DefaultKeyValue("sports", "00052IFG"));
        chantpc.add(new DefaultKeyValue("sports", "00052AFL"));
        chantpc.add(new DefaultKeyValue("sports", "00052IFD"));
        chantpc.add(new DefaultKeyValue("sports", "00052IFR"));
        chantpc.add(new DefaultKeyValue("sports", "00052IF7"));
        chantpc.add(new DefaultKeyValue("sports", "00051CB8"));
        chantpc.add(new DefaultKeyValue("sports", "00052IFC"));
//        chantpc.add(new DefaultKeyValue("sports", "00053UAR"));
//        chantpc.add(new DefaultKeyValue("sports", "000521B8"));
        chantpc.add(new DefaultKeyValue("sports", "00051CAT"));
        chantpc.add(new DefaultKeyValue("sports", "00051CB6"));
        chantpc.add(new DefaultKeyValue("sports", "00051L24"));
        chantpc.add(new DefaultKeyValue("sports", "00052IF4"));
        chantpc.add(new DefaultKeyValue("sports", "00051ROF"));
        chantpc.add(new DefaultKeyValue("sports", "00051CB5"));
        chantpc.add(new DefaultKeyValue("sports", "00051L23"));
        chantpc.add(new DefaultKeyValue("sports", "00051CB9"));
        chantpc.add(new DefaultKeyValue("sports", "00051CB7"));
        chantpc.add(new DefaultKeyValue("sports", "00051CDQ"));
        chantpc.add(new DefaultKeyValue("sports", "00051CDG"));
        chantpc.add(new DefaultKeyValue("sports", "00052UUC"));
        chantpc.add(new DefaultKeyValue("sports", "00051CA1"));
        chantpc.add(new DefaultKeyValue("sports", "00051C89"));
        chantpc.add(new DefaultKeyValue("sports", "00051C9Q"));
        chantpc.add(new DefaultKeyValue("tech", "000915BE"));
        chantpc.add(new DefaultKeyValue("tech", "000915BF"));
        chantpc.add(new DefaultKeyValue("tech", "000915BD"));
        chantpc.add(new DefaultKeyValue("finance", "00251LIE"));
        chantpc.add(new DefaultKeyValue("finance", "00251LJJ"));
        chantpc.add(new DefaultKeyValue("finance", "00254SU7"));
        chantpc.add(new DefaultKeyValue("finance", "00252G50"));
//        chantpc.add(new DefaultKeyValue("finance", "00252C1E"));
        chantpc.add(new DefaultKeyValue("finance", "002534NU"));
        chantpc.add(new DefaultKeyValue("finance", "002534NV"));
        chantpc.add(new DefaultKeyValue("finance", "002526O3"));
        chantpc.add(new DefaultKeyValue("finance", "002524SO"));
        chantpc.add(new DefaultKeyValue("finance", "002526O5"));
        chantpc.add(new DefaultKeyValue("finance", "00252H36"));
        chantpc.add(new DefaultKeyValue("finance", "00254SK6"));
        chantpc.add(new DefaultKeyValue("finance", "00252FE1"));

        List<DefaultKeyValue> newstpc = new ArrayList<DefaultKeyValue>();
        newstpc.add(new DefaultKeyValue("guonei", "0001124J"));
        newstpc.add(new DefaultKeyValue("guoji", "0001121M"));
        newstpc.add(new DefaultKeyValue("shehui", "00011229"));
        newstpc.add(new DefaultKeyValue("junshi", "00014OVF"));
//        newstpc.add(new DefaultKeyValue("hangkong", "00014P42"));
        chancol.put("news",newstpc);

        List<DefaultKeyValue> enttpc = new ArrayList<DefaultKeyValue>();
        enttpc.add(new DefaultKeyValue("mingxing", "00031H2L"));
        enttpc.add(new DefaultKeyValue("yinyue", "00034KRO"));
        enttpc.add(new DefaultKeyValue("dianshi", "00031GVS"));
        enttpc.add(new DefaultKeyValue("dianying", "000300B1"));
        chancol.put("ent",enttpc);

        List<DefaultKeyValue> sportstpc = new ArrayList<DefaultKeyValue>();
//        sportstpc.add(new DefaultKeyValue("zonghetiyu", "00051CAQ"));
        sportstpc.add(new DefaultKeyValue("zonghetiyu", "00051CBI"));
        sportstpc.add(new DefaultKeyValue("zonghetiyu", "00052IFL"));
//        sportstpc.add(new DefaultKeyValue("yishuticao", "00052IFL"));
        sportstpc.add(new DefaultKeyValue("zonghetiyu", "00053UBL"));
//        sportstpc.add(new DefaultKeyValue("gaoerfu", "00053UBL"));
        sportstpc.add(new DefaultKeyValue("saiche", "00051CAS"));
//        sportstpc.add(new DefaultKeyValue("zixingche", "00051CAS"));
        sportstpc.add(new DefaultKeyValue("zonghetiyu", "00052IF8"));
//        sportstpc.add(new DefaultKeyValue("jijian", "00052IF8"));
        sportstpc.add(new DefaultKeyValue("zonghetiyu", "00052IF6"));
//        sportstpc.add(new DefaultKeyValue("mashu", "00052IF6"));
        sportstpc.add(new DefaultKeyValue("zonghetiyu", "00052IFH"));
//        sportstpc.add(new DefaultKeyValue("saiting", "00052IFH"));
        sportstpc.add(new DefaultKeyValue("zonghetiyu", "00052IFE"));
//        sportstpc.add(new DefaultKeyValue("pihuating", "00052IFE"));
        sportstpc.add(new DefaultKeyValue("zonghetiyu", "00052IFB"));
//        sportstpc.add(new DefaultKeyValue("fanchuan", "00052IFB"));
        sportstpc.add(new DefaultKeyValue("zonghetiyu", "00052IFO"));
//        sportstpc.add(new DefaultKeyValue("bengchuang", "00052IFO"));
        sportstpc.add(new DefaultKeyValue("zonghetiyu", "0005038F"));
//        sportstpc.add(new DefaultKeyValue("ganlanqiu", "0005038F"));
        sportstpc.add(new DefaultKeyValue("zonghetiyu", "00052IFM"));
//        sportstpc.add(new DefaultKeyValue("qugunqiu", "00052IFM"));
        sportstpc.add(new DefaultKeyValue("zonghetiyu", "00052IFA"));
//        sportstpc.add(new DefaultKeyValue("shouqiu", "00052IFA"));
        sportstpc.add(new DefaultKeyValue("zonghetiyu", "00052IFG"));
//        sportstpc.add(new DefaultKeyValue("shejia", "00052IFG"));
        sportstpc.add(new DefaultKeyValue("zonghetiyu", "00052AFL"));
//        sportstpc.add(new DefaultKeyValue("sheji", "00052AFL"));
        sportstpc.add(new DefaultKeyValue("zonghetiyu", "00052IFD"));
//        sportstpc.add(new DefaultKeyValue("taiquandao", "00052IFD"));
        sportstpc.add(new DefaultKeyValue("zonghetiyu", "00052IFR"));
//        sportstpc.add(new DefaultKeyValue("roudao", "00052IFR"));
        sportstpc.add(new DefaultKeyValue("zonghetiyu", "00052IF7"));
//        sportstpc.add(new DefaultKeyValue("shuaijiao", "00052IF7"));
        sportstpc.add(new DefaultKeyValue("zonghetiyu", "00051CB8"));
//        sportstpc.add(new DefaultKeyValue("quanji", "00051CB8"));
        sportstpc.add(new DefaultKeyValue("zonghetiyu", "00052IFC"));
//        sportstpc.add(new DefaultKeyValue("juzhong", "00052IFC"));
//        sportstpc.add(new DefaultKeyValue("aoyun", "00053UAR"));
//        sportstpc.add(new DefaultKeyValue("liuxiang", "000521B8"));
        sportstpc.add(new DefaultKeyValue("zonghetiyu", "00051CAT"));
//        sportstpc.add(new DefaultKeyValue("bingxue", "00051CAT"));
        sportstpc.add(new DefaultKeyValue("zonghetiyu", "00051CB6"));
//        sportstpc.add(new DefaultKeyValue("ticao", "00051CB6"));
        sportstpc.add(new DefaultKeyValue("wangyuping", "00051L24"));
//        sportstpc.add(new DefaultKeyValue("yumaoqiu", "00051L24"));
        sportstpc.add(new DefaultKeyValue("zonghetiyu", "00052IF4"));
//        sportstpc.add(new DefaultKeyValue("youyongtiaoshu", "00052IF4"));
        sportstpc.add(new DefaultKeyValue("tianjing", "00051CB5"));
//        sportstpc.add(new DefaultKeyValue("tianjing", "00051CB5"));
        sportstpc.add(new DefaultKeyValue("wangyuping", "00051L23"));
//        sportstpc.add(new DefaultKeyValue("pingpang", "00051L23"));
        sportstpc.add(new DefaultKeyValue("taiqiu", "00051ROF"));
//        sportstpc.add(new DefaultKeyValue("taiqiu", "00051ROF"));
        sportstpc.add(new DefaultKeyValue("zonghetiyu", "00051CB9"));
//        sportstpc.add(new DefaultKeyValue("qipai", "00051CB9"));
        sportstpc.add(new DefaultKeyValue("paiqiu", "00051CB7"));
//        sportstpc.add(new DefaultKeyValue("paiqiu", "00051CB7"));
        sportstpc.add(new DefaultKeyValue("saiche", "00051CDQ"));
//        sportstpc.add(new DefaultKeyValue("f1", "00051CDQ"));
        sportstpc.add(new DefaultKeyValue("wangyuping", "00051CDG"));
//        sportstpc.add(new DefaultKeyValue("wangqiu", "00051CDG"));
        sportstpc.add(new DefaultKeyValue("cba", "00052UUC"));
        sportstpc.add(new DefaultKeyValue("nba", "00051CA1"));
        sportstpc.add(new DefaultKeyValue("guoneizuqiu", "00051C89"));
        sportstpc.add(new DefaultKeyValue("guojizuqiu", "00051C9Q"));
        chancol.put("sports",sportstpc);

        List<DefaultKeyValue> techtpc = new ArrayList<DefaultKeyValue>();
        techtpc.add(new DefaultKeyValue("tongxin", "000915BE"));
        techtpc.add(new DefaultKeyValue("hulianwang", "000915BF"));
        techtpc.add(new DefaultKeyValue("ityejie", "000915BD"));
        chancol.put("tech",techtpc);

        List<DefaultKeyValue> financetpc = new ArrayList<DefaultKeyValue>();
        financetpc.add(new DefaultKeyValue("zhengquan", "00251LIE"));
        financetpc.add(new DefaultKeyValue("zhengquan", "00251LJJ"));
        financetpc.add(new DefaultKeyValue("zhengquan", "00254SU7"));
        financetpc.add(new DefaultKeyValue("hongguan", "00252G50"));
//        financetpc.add(new DefaultKeyValue("hongguan", "00252C1E"));
        financetpc.add(new DefaultKeyValue("chanjing", "002534NU"));
        financetpc.add(new DefaultKeyValue("chanjing", "002534NV"));
        financetpc.add(new DefaultKeyValue("chanjing", "002526O3"));
        financetpc.add(new DefaultKeyValue("chanjing", "002524SO"));
        financetpc.add(new DefaultKeyValue("chanjing", "002526O5"));
        financetpc.add(new DefaultKeyValue("jinrong", "00252H36"));
        financetpc.add(new DefaultKeyValue("jinrong", "00254SK6"));
        financetpc.add(new DefaultKeyValue("chanjing", "00252FE1"));
//        financetpc.add(new DefaultKeyValue("jijin", "00254ROU"));
//        financetpc.add(new DefaultKeyValue("licai", "00254SUA"));


//        financetpc.add(new DefaultKeyValue("hongguan", "00254STB"));
//        financetpc.add(new DefaultKeyValue("chanjing", "00254SM1"));
//        financetpc.add(new DefaultKeyValue("chanjing", "00254STC"));
//        financetpc.add(new DefaultKeyValue("zhengquan", "00254STE"));
//        financetpc.add(new DefaultKeyValue("jinrong", "00254SM3"));
//        financetpc.add(new DefaultKeyValue("jinrong", "00254STD"));


        chancol.put("finance",financetpc);

        List<DefaultKeyValue> traveltpc = new ArrayList<DefaultKeyValue>();
        traveltpc.add(new DefaultKeyValue("jingnei", "00064L21"));
        traveltpc.add(new DefaultKeyValue("jingnei", "00063IB2"));
        traveltpc.add(new DefaultKeyValue("jingnei", "00061DP9"));
        traveltpc.add(new DefaultKeyValue("jingnei", "00061DP6"));
        traveltpc.add(new DefaultKeyValue("jingnei", "00061DP8"));
        traveltpc.add(new DefaultKeyValue("jingnei", "00061DP7"));
        traveltpc.add(new DefaultKeyValue("jingnei", "00061DP5"));
        traveltpc.add(new DefaultKeyValue("jingnei", "00061DPB"));
        traveltpc.add(new DefaultKeyValue("jingnei", "00061DPA"));
        traveltpc.add(new DefaultKeyValue("chujing", "00064L22"));
        traveltpc.add(new DefaultKeyValue("chujing", "00063IB3"));
        traveltpc.add(new DefaultKeyValue("chujing", "00061DOT"));
        traveltpc.add(new DefaultKeyValue("chujing", "00061DP0"));
        traveltpc.add(new DefaultKeyValue("chujing", "00061DOV"));
        traveltpc.add(new DefaultKeyValue("chujing", "00061DP2"));
        traveltpc.add(new DefaultKeyValue("chujing", "00061DOU"));
        traveltpc.add(new DefaultKeyValue("chujing", "00061DP1"));
        traveltpc.add(new DefaultKeyValue("chujing", "00061DP4"));
        traveltpc.add(new DefaultKeyValue("meishi", "00064L23"));
        traveltpc.add(new DefaultKeyValue("meishi", "00063IBL"));
        traveltpc.add(new DefaultKeyValue("meishi", "00064LG8"));
        traveltpc.add(new DefaultKeyValue("meishi", "00064LG7"));
        traveltpc.add(new DefaultKeyValue("huwai", "00064L24"));
//        traveltpc.add(new DefaultKeyValue("huwai", "00063IBJ"));
        traveltpc.add(new DefaultKeyValue("huwai", "00061PU7"));
//        traveltpc.add(new DefaultKeyValue("huwai", "00061Q90"));
//        traveltpc.add(new DefaultKeyValue("huwai", "00061Q93"));
//        traveltpc.add(new DefaultKeyValue("huwai", "00061Q92"));
//        traveltpc.add(new DefaultKeyValue("huwai", "00061Q91"));
//        traveltpc.add(new DefaultKeyValue("huwai", "00061Q96"));
//        traveltpc.add(new DefaultKeyValue("huwai", "00061Q94"));
//        traveltpc.add(new DefaultKeyValue("huwai", "00061Q95"));
//        traveltpc.add(new DefaultKeyValue("huwai", "00061Q5F"));
//        traveltpc.add(new DefaultKeyValue("huwai", "00064KM7"));
//        traveltpc.add(new DefaultKeyValue("huwai", "00064KMQ"));
//        traveltpc.add(new DefaultKeyValue("huwai", "00064KMS"));
//        traveltpc.add(new DefaultKeyValue("huwai", "00064KMR"));
//        traveltpc.add(new DefaultKeyValue("huwai", "00064KM9"));
//        traveltpc.add(new DefaultKeyValue("huwai", "00064KMA"));
//        traveltpc.add(new DefaultKeyValue("huwai", "00064KMF"));
//        traveltpc.add(new DefaultKeyValue("huwai", "00064KME"));
//        traveltpc.add(new DefaultKeyValue("huwai", "00064KMG"));
        traveltpc.add(new DefaultKeyValue("huwai", "00064KMI"));
        traveltpc.add(new DefaultKeyValue("huwai", "00064KMJ"));
//        traveltpc.add(new DefaultKeyValue("huwai", "00064KML"));
//        traveltpc.add(new DefaultKeyValue("huwai", "00064KMM"));
//        traveltpc.add(new DefaultKeyValue("huwai", "00061GRA"));
//        traveltpc.add(new DefaultKeyValue("huwai", "00061GIS"));
        traveltpc.add(new DefaultKeyValue("huwai", "00061GIR"));
//        traveltpc.add(new DefaultKeyValue("huwai", "00061GHL"));
        traveltpc.add(new DefaultKeyValue("huwai", "00061GHK"));
//        traveltpc.add(new DefaultKeyValue("huwai", "00061GHO"));
//        traveltpc.add(new DefaultKeyValue("huwai", "00061GOC"));
//        traveltpc.add(new DefaultKeyValue("huwai", "00061GO9"));
//        traveltpc.add(new DefaultKeyValue("huwai", "00061GOB"));
//        traveltpc.add(new DefaultKeyValue("huwai", "00061GOA"));
//        traveltpc.add(new DefaultKeyValue("huwai", "00061GO8"));
//        traveltpc.add(new DefaultKeyValue("huwai", "00061GOF"));
//        traveltpc.add(new DefaultKeyValue("huwai", "00061GOE"));
//        traveltpc.add(new DefaultKeyValue("huwai", "00061GOD"));
//        traveltpc.add(new DefaultKeyValue("zixun", "00064L1K"));
//        traveltpc.add(new DefaultKeyValue("zixun", "00063K6N"));
//        traveltpc.add(new DefaultKeyValue("zixun", "00063IM3"));
//        traveltpc.add(new DefaultKeyValue("zixun", "00063IBC"));
//        traveltpc.add(new DefaultKeyValue("zixun", "00064L1M"));
//        traveltpc.add(new DefaultKeyValue("zixun", "00064L1N"));
//        traveltpc.add(new DefaultKeyValue("zixun", "00064L1L"));
        chancol.put("travel",traveltpc);


        List<DefaultKeyValue> wartpc = new ArrayList<DefaultKeyValue>();
        wartpc.add(new DefaultKeyValue("zhoubian", "00014OL0"));
        wartpc.add(new DefaultKeyValue("guoji", "00013CP0"));
        wartpc.add(new DefaultKeyValue("zhongguo", "00013COV"));
        wartpc.add(new DefaultKeyValue("taihai", "00014OL1"));
        chancol.put("war",wartpc);


        List<DefaultKeyValue> airtpc = new ArrayList<DefaultKeyValue>();
        airtpc.add(new DefaultKeyValue("minhang", "00014P24"));
        airtpc.add(new DefaultKeyValue("tongyong", "00014RRJ"));
        airtpc.add(new DefaultKeyValue("gongwu", "00014RRK"));
        airtpc.add(new DefaultKeyValue("fangwu", "00014RRI"));
        airtpc.add(new DefaultKeyValue("gongye", "00014P26"));
        airtpc.add(new DefaultKeyValue("hangtian", "00014P27"));
        chancol.put("air",airtpc);


        List<DefaultKeyValue> stocktpc = new ArrayList<DefaultKeyValue>();
        stocktpc.add(new DefaultKeyValue("qihuo", "0025448R"));
        stocktpc.add(new DefaultKeyValue("waihui", "0025448T"));
        stocktpc.add(new DefaultKeyValue("xingu", "00252EEK"));
        stocktpc.add(new DefaultKeyValue("xingu", "00253E5C"));
        stocktpc.add(new DefaultKeyValue("chuangyeban", "00253AOI"));
        stocktpc.add(new DefaultKeyValue("chuangyeban", "00253AOJ"));
        stocktpc.add(new DefaultKeyValue("chuangyeban", "00253G91"));
        stocktpc.add(new DefaultKeyValue("chuangyeban", "00253GAL"));
        stocktpc.add(new DefaultKeyValue("meigu", "00253CVK"));
        stocktpc.add(new DefaultKeyValue("ougu", "00252V5H"));
        stocktpc.add(new DefaultKeyValue("yagu", "00252V5G"));
        stocktpc.add(new DefaultKeyValue("zhonggaigu", "00253K1O"));
        stocktpc.add(new DefaultKeyValue("ganggu", "00254445"));
        chancol.put("stock",stocktpc);
    }
}
